snowflake-dw:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: yv99219.us-central1.gcp

      #User/password auth
      user: FELIPE
      password: **************

      role: @@@@@@@@@@@@@@@@@
      database: @@@@@@@@@@@@
      warehouse: @@@@@@@@@@@@@
      schema: AIRBYTE_SCHEMA
      threads: 1
      client_session_keep_alive: False
      query_tag: dbt-q

      # optional
      connect_retries: 0 #default 0
      connect_timeout: 10
      retry_on_database_errors: False
      retry_all: False